#!/bin/bash
# put in /etc/init.d/open-iscsi in the stemcell
### BEGIN INIT INFO
# Provides:          open-iscsi
# Required-Start:    $remote_fs nfs-common
# Required-Stop:     $remote_fs nfs-common
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: open-iscsi fake for bosh agent
# Description:       Fakes open-iscsi for the bosh agent
#                    mounts nfs and creates loopback devices pointing to disk.img on nfs eport
### END INIT INFO

jsonPath="/piConfig/disks.json"
I=0

for diskJson in $(jq -c '.[]' $jsonPath)
do
  location=$(echo $diskJson | jq ".location")
  id=$(echo $diskJson | jq ".id")
  nfsaddress=$(echo $diskJson | jq ".nfsAddress")
  mountpoint="/mnt/${id//\"/}"
  diskpath=$mountpoint/disk.img

  mkdir $mountpoint
  mount -t nfs ${nfsaddress//\"/}:${location//\"/} $mountpoint

  kpartx -av -p "-part" $diskpath

  sleep 10s

  ln -s /dev/mapper/loop${I}-part1 /dev/mapper/loop${I}1
  ln -s /dev/mapper/loop${I}-part2 /dev/mapper/loop${I}2

  ln -s /dev/loop${I} /dev/mapper/loop${I}

   ((++I))
done

exit 0
